include classpath("application.conf")

node-address {
  protocol = http
  host     = "*"
  port     = 9324
}

rest-sqs {
  enabled       = true
  bind-port     = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits    = strict
}

queues {
  integration-inbound {
    defaultVisibilityTimeout = 30 seconds
    receiveMessageWait       = 20 seconds
    deadLettersQueue {
      name           = integration-dlq
      maxReceiveCount = 3
    }
  }

  integration-dlq {
    defaultVisibilityTimeout = 30 seconds
  }
}